apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zI3u9AjSyfs=,iv:80Ows5ROUr9FBQ2VYf7bfHuMOIk/O5Gp4sKSqJEy9/g=,tag:0arLri9eBvnQiqh62qyZKQ==,type:str]
    user: ENC[AES256_GCM,data:EKsQxVlgfmA=,iv:jLN89nTjSVx0smZvdt1WlWo1oiENQpH1FXTZydzG6HY=,tag:GPJly1S1WplWajLK8iFjNQ==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5R3dCYmRPRzMyZXliSUVy
            RXROTU93ejRvRXd5a0dNWjU3MWM4VXBSMUVjCjc3cUVOdnh6WmpsbXVBaFQ2enZm
            aUdTRmEvcll4MWE0a0QzYU9vaDhVa0kKLS0tIDl0MURxVFp6YUZsMFpva3g2YXVi
            QVZSK0NkbXBnM0FOaE5HWXA1NVhyaDQKNn/93k9nhfeh5Fcg3d9AP/CTLvbhy9iq
            crJKoOTybSYMigOrnbwTy7BGntST+tLeiEN+SRcjelNmy8eIWlTDVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gwffkh8raau2nptu36sa99ejnmf0akp25llj2fjfv5dtkyvuy47qqwnm6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T19:22:43Z"
    mac: ENC[AES256_GCM,data:YK+zlXpPxGUUatd4wXBTGhd5P8TyYOtebHn9TK/majEp4etQ+LzzxneQUzo+Btb6tCK/yV1lktUmU93Rtuo7fCC9kHSeYjMTaqnj0+96rHXkNM2otPUYN7Cu2Tue5oZo/fDvKeuGjWJD2hJcP8md/R4uiGBQWXe7rDpk4U+vqko=,iv:gkNbl8OqmIHvbOf+qMl7EWATvrKmiTPmb/vdqu1h9iM=,tag:Zz2tElfptEXzXKn3PwjvBw==,type:str]
    version: 3.13.3
