apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:J8GpvWHCyVvuI7pGBa9Z6ZZ7nrMsPLhtFo+UbOFRouh7y/5KsKbz3xvWm495Rzd99UoW7DGeWMAulRgTEhz3Opw/dFl26iLJQbvQByuxVsIO7oNSxtnsj7DWjPIj/lRMtJvZrU+0NZbqN2LJkcXR5sUEhg83l+EF63K71xMHyiEyqpXAP8LUIL0uZdMOZO4hvYSTq99QRIVNgHYupTdRBfkHI8iCmuRcF0RfBeJhEkO/CKB0w1t5rc1lnobI4zPQ3f4D+NAGjfZjwz5Sl5Z4aS9XyFNP/wxmoAIt9dYI1tuOBY8qJ8yJvgTbcvo=,iv:CxAJTTmD76cog0SrhidwdAG20kesP6IEJLh1zdgjSiU=,tag:8brr5wDK1IEaaPNWqBLY5w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWWhyb3djcnFNZTRoak9s
            N1QrcGVVci8xbWhXME9pRkdSM3U1T2tmelJFCjd4T1dEWWtCWENJN3pUdGhOdUNu
            VzlmcEdwRVIwV2xLRU9yVlZ4NUZpclEKLS0tIHhpRmRlUTlwdFo1TFZpeXBYK05E
            VlBmcjJ1Zk40QjlEbG53VVk2Uk8za1UKKaeZ+dJ43LJinAMcEtirRSQuVT2Mn4WC
            fVwfIOMvZlS42SqfbdpMPq19Mn29A7yiopz/se8YJF5xBFje1dzDbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gwffkh8raau2nptu36sa99ejnmf0akp25llj2fjfv5dtkyvuy47qqwnm6a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T04:43:56Z"
    mac: ENC[AES256_GCM,data:fDIAJSVPNIitqCWQmuvhrjTFy0hfGIdS+9sV4v5Z+oPwGqtyLdTiArgPxzVlc9KlgxOId6pZ5iDkZY+BX2fp48hNkYRfyj1tOA6jhPBtsfLnfzNsjAWqwA9z6AxsoldSCr2sYGwCjPayV6KquRv03L89W4gcWL+L+V1Vd+ZiUO4=,iv:2kGfU/JjHPQBb3GlT7rdDDwIncMsP3GRt735UETeWa4=,tag:z4i8HYHnnYGYEzzENKMEVg==,type:str]
    version: 3.13.3
